### ISSUE TITLE
[Bug]: webR box too wide

### ISSUE THREAD

**Issue by dlsun** [coatless/quarto-webr#106]
### Bug description

Thanks for fixing the issue with the webR box being too tall!

However, the webR box still appears to be too wide. See the screenshot below, with the scrollbar at the bottom.

<img width="1087" alt="Screenshot 2023-11-17 at 10 23 47 AM" src="https://github.com/coatless/quarto-webr/assets/1175502/d6250ab9-bb64-4b16-9241-38b8612f4bb3">

### Steps to reproduce

````
---
title: Testing 0.4.0
engine: knitr
format: 
  revealjs:
    resources:
    - webr-serviceworker.js
    - webr-worker.js
webr:
  channel-type: "automatic"
filters:
  - webr
---

## Slide with webR {.scrollable}

```{webr-r}
2 + 3
```

The default webR block makes the slide too wide 
(see the scrollbar at the bottom).
````

### Your environment

- MacOS Sonoma 14.0
- RStudio 2023.09.0+463
- Chrome 119.0.6045.123
