### ISSUE TITLE
[Q&A] How can I change output background?

### ISSUE THREAD

**Issue by jgeller112** [coatless/quarto-webr#156]
### What's your question?

How can I change the background of the output? I have a black background on my slides and the output does not show up clearly.

**Comment by jgeller112** [comment]
In older version, it would output on white background.

**Comment by coatless** [comment]
You should be able to change the background color by doing either:

```yaml
format:
  html:
    css:
      - "webr.css"
 ```

Then, in `webr.css`, you could use:

```css
.qwebr-output-code-area {
   background-color: white
}
```

Otherwise, you could include the inline style change with:

```yaml
format:
  html:
    include-in-header:
      - text: |
          <style> .qwebr-output-code-area { background-color: white} </style>
```

The full list of supported CSS classes may be found at:

https://quarto-webr.thecoatlessprofessor.com/qwebr-theming.html

For an example of overriding more styling options, please see: 

https://jamesgoldie.dev/writing/your-new-r-package-webr/

https://github.com/jimjam-slam/jamesgoldie-dev/tree/6b60b2e42c6e21eb1ed8ae390f108592bb48d98c/writing/your-new-r-package-webr

**Comment by jgeller112** [comment]
I placed the above code in my css file but no luck

<img width="1190" alt="Screen Shot 2024-02-15 at 2 56 35 PM" src="https://github.com/coatless/quarto-webr/assets/18429968/c4529d3b-7de0-4116-91de-178e2c7c5e71">

**Comment by coatless** [comment]
@jgeller112 can you link me over to a slide deck?

**Comment by jgeller112** [comment]
Here is my qmd file: https://github.com/jgeller112/PSY504-Advanced-Stats-S24/blob/main/slides/04-logistic/logisticqmd.qmd

Here is css file I am using: https://github.com/jgeller112/PSY504-Advanced-Stats-S24/blob/main/slides/04-logistic/slide-style.css

**Comment by coatless** [comment]
@jgeller112 opened a PR here: 

https://github.com/jgeller112/PSY504-Advanced-Stats-S24/pull/1

Short-gist, we needed to go from:

```css
.qwebr-output-code-area {
   background-color: white
}
```

to

```css
.reveal div.qwebr-output-code-area pre {
   background-color: white;
}
```
