### ISSUE TITLE
Add `version` document option

### ISSUE THREAD

**Issue by coatless** [coatless/quarto-webr#211]
Allow for specifying the version of main [webR project](https://docs.r-wasm.org/) to be used. 

- `latest`
- `v0.3.3`
- and so on 

This is a toggle to ensure documents work well when the version of R is boosted; but the extension isn't running the latest version.

**Comment by coatless** [comment]
We probably should add this.

But, the main driver was needing to specify `webr-image` under the action build recipe for `build-rwasm`.

```yml
      - name: Build WASM R packages
        uses: r-wasm/actions/build-rwasm@v1
        with:
          packages: "."
          repo-path: "_site"
          webr-image: "ghcr.io/r-wasm/webr:v0.3.3"
```

c.f. https://github.com/r-wasm/actions/issues/22 and https://github.com/r-wasm/rwasm/issues/33
