### ISSUE TITLE
Global state for extensions

### ISSUE THREAD

**Issue by coatless** [coatless/quarto-webr#46]
During private discussions, we had a few requests to allow for setting a global option to avoid re-specifying the same YAML header information on a course website. This is relevant with respect to disabling the status indicator, setting the communication channel, and specifying a pre-set amount of R packages.

I'm not sure such a feature is viable in the current Quarto build. My best guess here would be to add an extension configuration, e.g. `_quarto-extension.yml`, that contains the options preset.

```yml
extension:
  - webr:
        channel-type: post-message
        channel-type: post-message
```
